export const STR = {
  title: "chibikart",
  connecting: "connecting...",
  reconnecting: "connection lost, reconnecting...",
  waitingRoom: "waiting room",
  inviteHint: "send this link to a friend to race",
  copy: "copy",
  copied: "copied",
  ready: "ready",
  unready: "not ready",
  waitingForPlayers: "waiting for at least 2 players...",
  waitingForReady: "waiting for everyone to ready up...",
  spectating: "race in progress, you are watching",
  raceLost: "the room restarted, ready up to race again",
  go: "GO",
  lap: "lap",
  wrongWay: "wrong way",
  finished: "finished",
  results: "results",
  playAgain: "play again",
  youAre: "you are",
  place: ["1st", "2nd", "3rd", "4th"],
  kartNames: { red: "red", blue: "blue", green: "green", yellow: "yellow" },
  errors: {
    room_full: "room is full, you are watching",
    bad_action: "that did not work, try again",
  },
  controls: "drive: WASD or arrows. drift: space or shift. touch: left side steers, right side buttons.",
};
